 name = "airtable-do"
route = { pattern = "*/*", zone_name = "airtable.do" }
main = "dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2022-09-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
 
kv_namespaces = [
  { binding = "STORAGE", id = "000" }
]

workers_dev = false
logpush = true

[build]
command = "npm run build"
 
[build.upload]
format = "modules"

[miniflare]
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"